# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
  disable:
    - exhaustruct
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          allow:
            - $gostd
            - github.com/fire-ant/kro-actions-runner/cmd/kar/app
            - github.com/fire-ant/kro-actions-runner/internal
            - github.com/golang/mock/gomock
            - github.com/pkg/errors
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - k8s.io/api/core/v1
            - k8s.io/apimachinery/pkg/api/errors
            - k8s.io/apimachinery/pkg/apis/meta/v1
            - k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
            - k8s.io/apimachinery/pkg/runtime/schema
            - k8s.io/apimachinery/pkg/watch
            - k8s.io/client-go/dynamic
            - k8s.io/client-go/kubernetes
            - k8s.io/client-go/tools/clientcmd
            - k8s.io/utils/ptr
            - kubevirt.io/api/core/v1
            - kubevirt.io/client-go/containerizeddataimporter/fake
            - kubevirt.io/client-go/kubecli
            - kubevirt.io/client-go/kubevirt/fake
            - kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1
            - github.com/onsi/ginkgo/v2
            - github.com/onsi/gomega
            - github.com/matryer/resync
    gomoddirectives:
      replace-allow-list:
        - k8s.io/kube-openapi

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - revive
          - errcheck
        text: "dot-imports:"

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - file

run:
  timeout: 5m
  tests: true
  go: "1.25"
