apiVersion: v1
kind: Secret
metadata:
  name: test-ec2-runner
  namespace: default
type: Opaque
stringData:
  .jitconfig: |
    {
      "url": "https://github.com/test/test",
      "runner_name": "test-ec2-runner",
      "runner_group_name": "default",
      "labels": ["test", "ec2", "localstack"],
      "jit_config": "test-token-12345"
    }
