apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: vpc-network
spec:
  schema:
    apiVersion: v1alpha1
    kind: VPCNetwork
    spec:
      # VPC CIDR block
      cidrBlock: string | default = "10.0.0.0/16"
      # Subnet CIDR block
      subnetCidrBlock: string | default = "10.0.1.0/24"
      # Name tag for resources
      name: string
  resources:
    # VPC
    - id: vpc
      template:
        apiVersion: ec2.services.k8s.aws/v1alpha1
        kind: VPC
        metadata:
          name: ${schema.spec.name}-vpc
        spec:
          cidrBlocks:
            - ${schema.spec.cidrBlock}
          enableDNSSupport: true
          enableDNSHostnames: true
          tags:
            - key: Name
              value: ${schema.spec.name}-vpc
    # Internet Gateway
    - id: internetGateway
      template:
        apiVersion: ec2.services.k8s.aws/v1alpha1
        kind: InternetGateway
        metadata:
          name: ${schema.spec.name}-igw
        spec:
          vpcRef:
            from:
              name: ${vpc.metadata.name}
          tags:
            - key: Name
              value: ${schema.spec.name}-igw
    # Subnet
    - id: subnet
      template:
        apiVersion: ec2.services.k8s.aws/v1alpha1
        kind: Subnet
        metadata:
          name: ${schema.spec.name}-subnet
        spec:
          cidrBlock: ${schema.spec.subnetCidrBlock}
          vpcRef:
            from:
              name: ${vpc.metadata.name}
          tags:
            - key: Name
              value: ${schema.spec.name}-subnet
    # Security Group
    - id: securityGroup
      template:
        apiVersion: ec2.services.k8s.aws/v1alpha1
        kind: SecurityGroup
        metadata:
          name: ${schema.spec.name}-sg
        spec:
          name: ${schema.spec.name}-sg
          description: Security group for ${schema.spec.name}
          vpcRef:
            from:
              name: ${vpc.metadata.name}
          ingressRules:
            - fromPort: 22
              toPort: 22
              ipProtocol: tcp
              ipRanges:
                - cidrIP: "0.0.0.0/0"
                  description: "SSH access"
          egressRules:
            - ipProtocol: "-1"
              ipRanges:
                - cidrIP: "0.0.0.0/0"
                  description: "Allow all outbound"
          tags:
            - key: Name
              value: ${schema.spec.name}-sg
